services:
  db:
    image: postgres
    container_name: django_tenants_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432