[project]
name = "tenants-demo"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "django-debug-toolbar>=6.0.0",
    "django-environ>=0.12.0",
    "django-extensions>=4.1",
    "psycopg>=3.2.11",
]
